### ISSUE TITLE
Re-structure error handling

### ISSUE THREAD

**Issue by fennifith** [TheAndroidMaster/Pasta-for-Spotify#10]
Currently there are only two types of errors: ones from the Service that create toast messages, and network errors that create dialogs to force the user to restart the app. This was only a temporary fix to prevent the app from getting stuck in a loop. I would like to eventually make a better error handling system that automatically handles a few common issues:
- [x] re-initialize the SpotifyService if something weird happens
- [x] wait for a bit then re-send requests if a 429 (too many requests) error is returned
- [x] I've also received a couple 502 and 520 errors, these should have the same result as 429 (hopefully no 400's will be found) (or 418)
- [x] for other network issues, check the connection then either show a snackbar if the device is disconnected or call onBackPressed() for anything else (example: trying to enter a playlist that was just  deleted)
- [x] automatically re-create the PlayerService if we run into the 'Unknown error, please restart the app' problem

**Comment by PDDStudio** [comment]
A broadcast receiver for getting notified about network changes might be helpful, too. Check this guide: https://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html

**Comment by fennifith** [comment]
Last thing to do here is switch unimportant issues to a snackbar instead of using a dialog...

**Comment by fennifith** [comment]
Welp, with commit 8ade81f I've replaced most of the toasts and dialogs with snackbar-styled toasts so I think this can be closed now...
