### ISSUE TITLE
Make the PlayerService in another process.

### ISSUE THREAD

**Issue by alexandrepiveteau** [TheAndroidMaster/Pasta-for-Spotify#14]
I thought it could drastically improve the memory management of the application to have two separate processes for the PlayerService and the rest of the app. This way, when something is playing in the background, the system is free to destroy the activities and kill the UI-related process, while the music keeps playing in the background.

This also means that you would need to ensure that your service uses only [Intents](https://www.youtube.com/watch?v=cU8HrO7XuiE) or [AIDL](https://youtu.be/2-RXGg8hbJM) to communicate with the [process](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

**Comment by fennifith** [comment]
Fixed in commit 5469852
