### ISSUE TITLE
APK files in releases show wrong version number

### ISSUE THREAD

**Issue by IzzySoft** [TheAndroidMaster/Pasta-for-Spotify#15]
Starting with v1.3, they all have the same line in their Manifest:

```
package: name='pasta.streamer' versionCode='4' versionName='1.3'
```

(this is from 1.4 and 1.5). Will cause issues on updates and other confusion :)

**Comment by fennifith** [comment]
Not sure how you managed to get that, or how to change it. The version code and name are set in [app/build.gradle](https://github.com/TheAndroidMaster/Pasta-for-Spotify/blob/master/app/build.gradle), not the manifest. I'm not completely sure, but I think you're looking in the wrong place:

> [If your app defines the app version directly in the <manifest> element, the version values in the Gradle build file will override the settings in the manifest.](https://developer.android.com/studio/publish/versioning.html)

**Comment by IzzySoft** [comment]
```
CRITICAL: duplicate versions: 'pasta.streamer_1.4.apk' - 'pasta.streamer_1.5.apk'
```

Try `aapt d badging pasta.streamer_1.4.apk | head -n 1` to see for yourself.

Yuck, strike that – error on my end. Script grabbed the wrong version (need to check how that happened). Sorry for the confusion!

Edit: Fixed (on my end). A page with only pre-releases has no "latest" section – so it took the "last" file instead =:-0
