### ISSUE TITLE
Invalid Client

### ISSUE THREAD

**Issue by nico151999** [TheAndroidMaster/Pasta-for-Spotify#23]
Making a release build using gradlew build doesn't work at all and if I make a debug build I get the message "Invalid Client" when I try to log in. I have to admit that I haven't even watched the source of the App yet, thus I don't know what might cause such issues. Anyway, it is currently unusable. Are you conscious of that? Is the work on the project still progressing? Would be nice to know as this app's got lots of potential.

Looking forward to an answer, thanks!

**Comment by fennifith** [comment]
You need to specify a client id [here](https://github.com/TheAndroidMaster/Pasta-for-Spotify/blob/master/app/src/main/java/pasta/streamer/Pasta.java#L42) before building the app ;)

(I should probably put this in the readme lol)

**Comment by nico151999** [comment]
Aah, great, will try to figure out how to create one. Thanks.
The other issue:
Running a release build fails by default, I saw that shrinkresources is enabled in your build.gradle for the release build. However, ist seems like shrinkresources does not work without minifyenabled set to true. In earlier graddle versions there were only warnings and nothing happened having only shrinkresources set to true but since 2.2, I think, gradle fails to build if only shrinkresources is set to true. Seting minifyenabled to true ends up with another build error I haven't analysed so far. Removing minifyenabled and shrinkresources causes another build error which can be circumvented by ignoring some errors output by lint.

**Comment by fennifith** [comment]
@nico151999 thanks!
I probably won't get around to fixing the other issue until I actually need to make another release. The project is currently a bit disorganized and has a few major issues that will need to be fixed before the next version (see issues #18 and #22), and at the moment I'm lacking both the time and commitment needed to fix them :P
